# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/vagrant/.oh-my-zsh"

CARGO_BIN=$HOME/.cargo/bin
POETRY=$HOME/.poetry/bin
CUSTOM_BIN=$HOME/.bin
PYENV_BIN=$HOME.pyenv/bin
export PATH=$CARGO_BIN:$PYENV_BIN:$POETRY:$CUSTOM_BIN:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:$PATH

ZSH_THEME="miloshadzic"
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  common-aliases
  tmux
  ripgrep
  cargo
  rust
  rustup
  pyenv
  fzf
  fd
  wd
  redis-cli
  docker
  docker-compose
)

source $ZSH/oh-my-zsh.sh

# User configuration

export LANG=en_US.UTF-8
export EDITOR=nvim
export PYTHONSTARTUP=~/.pythonrc
export POETRY_VIRTUALENVS_IN_PROJECT=true

unalias fd
alias vi=/usr/bin/vim
alias vim=nvim
alias pcr="pre-commit run"
alias ls="exa"
alias la="ls -alh"
alias rga="rg -A 1"
alias git-clean="git branch -v | rg -v '\*' | rg \"\\[gone\\]\" | awk '{print $1; }' | xargs -r git branch -D"
alias cat=bat
alias find=fd

# pyenv should be loaded by oh-my-zsh
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
eval "$(starship init zsh)"

source /opt/rh/rh-git218/enable

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
