# Path to your oh-my-zsh installation.
export ZSH=/home/$USER/.oh-my-zsh

CARGO_BIN=$HOME/.cargo/bin
POETRY=$HOME/.poetry/bin
CUSTOM_BIN=$HOME/.bin
PYENV_BIN=$HOME/.pyenv/bin
NVIM_BIN=$HOME/.bin/nvim-linux64/bin
TOOLS=$HOME/tools
CODE=$HOME/VSCode-linux-x64/bin
TOOLS_BIN=$HOME/remote-home/tools/bin
export PATH=$TOOLS_BIN:$NVIM_BIN:$CODE:$CARGO_BIN:$PYENV_BIN:$POETRY:$CUSTOM_BIN:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:$PATH
export TERMINFO=/usr/share/terminfo
export LD_LIBRARY_PATH=$HOME/remote-home/tools/lib:$LD_LIBRARY_PATH

ZSH_THEME="miloshadzic"
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(
  git
  common-aliases
  ripgrep
  cargo
  rust
  rustup
  # pyenv
  fzf
  fd
  wd
  redis-cli
  docker
  docker-compose
)

source $ZSH/oh-my-zsh.sh

# User configuration

export LANG=en_US.UTF-8
export EDITOR=nvim
export PYTHONSTARTUP=~/.pythonrc
export POETRY_VIRTUALENVS_IN_PROJECT=true
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export BAT_THEME="gruvbox-dark"

unalias fd 2>/dev/null
alias vi=/usr/bin/vim
alias vim=nvim
alias pcr="pre-commit run"
alias ls="exa"
alias la="ls -alh"
alias rga="rg -A 1"
alias git-clean="git fetch -p && git branch -vv | rg -v '\*' | awk '/: gone]/{print $1}' | xargs -r git branch -D"
alias cat=bat
alias find=fd

# pyenv should be loaded by oh-my-zsh
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
eval "$(starship init zsh)"

source /opt/rh/rh-git218/enable
source /opt/rh/rh-postgresql10/enable

if [ -n "$PYTHONPATH" ]; then
    export PYTHONPATH='/home/rhanson/.local/share/pdm/venv/lib64/python3.8/site-packages/pdm/pep582':$PYTHONPATH
else
    PYTHONPATH='/home/rhanson/.local/share/pdm/venv/lib64/python3.8/site-packages/pdm/pep582'
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
